

services:
  api:
    build:
      context: ./app
    
    container_name: task-api
    ports:
      - "3000:3000"
    environment:
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: password123
      PG_DB: taskdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: taskdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: