apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskdb
  template:
    metadata:
      labels:
        app: taskdb
    spec:
      containers:
        - name: taskdb
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password123
            - name: POSTGRES_DB
              value: taskdb
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
