apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: simple_design-api:latest
          imagePullPolicy: IfNotPresent   
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: taskdb-service       
            - name: PG_USER
              value: postgres
            - name: PG_PASSWORD
              value: password123
            - name: PG_DB
              value: taskdb